s="This is my cat, where is your cat, the cat is cute"
print("uppercase",s.upper())
print("lowercase",s.lower())
pos=s.find("cat")
print("the position : ",pos)
pos=s.find("cat",pos+1)
print("the position : ",pos)
pos=s.find("cat",pos+1)
print("the position : ",pos)
pos=s.find("cat",pos+1)
print("the position : ",pos)
